---
- name: Install Docker and Pip
  hosts: webservers
  become: true
  roles:
    - install_docker

- name: Deploy Redmine
  hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - deploy_redmine

- name: Configure DataDog
  hosts: webservers
  become: true
  roles:
    - DataDog.datadog